# Generated by Django 5.0.3 on 2024-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_doc',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
