# Generated by Django 5.0.3 on 2024-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_book_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_doc',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
